/*
DOCUMENTATION TO WORK WITH APPLICATION
------------------------------------------------

EDITOR CREATES PLANE OBJECTS.
TO INTERACT WITH EDITOR AND OBJECTS YOU MUST USE HOTKEYS.

HOTKEYS:
	
	ZOOM: 
		"-" ZOOM OUT
		"+" ZOOM IN

	TO CHOOSE COLOR FOR OBJECT, INTERACT WITH RGB-PALETTE IN TOP-LEFT CORNER
	IF YOU WANT MORE RED COLOR, CLICK LEFT CIRCLE/BUTTON
	IF YOU WANT MORE GREEN COLOR, CLICK CENTRE CIRCLE/BUTTON
	IF YOU WANT MORE BLUE COLOR, CLICK RIGHT CIRCLE/BUTTON
	P.S. That's why it's RGB :0

	YOU CAN CREATE OBJECTS BY POINTS. 
	IF YOU CREATED OBJECT, YOU INTERACT WITH HIM OR ALREADY CREATE NEW ONE

	YOU CAN CREATE POINTS ON PLANE BY CLICKING LEFT MOUSE BUTTON
	IF THERE ARE MORE THAN 3 POINTS WHEN YOU CREATE NEW OBJECT,
	YOU WILL BUILD TRIANGLE OR POLYGON (ONLY CONVEX) BY CLICKING "ENTER" BUTTON

	ELSE IF YOU WANT ONLY ONE POINT, CLICK LEFT MOUSE BUTTON AND CLICK "ENTER" BUTTON
	
	ELSE IF THERE ARE 2 POINTS, YOU CAN CREATE OBJECTS: LINE, SEGMENT, RAY, CIRCLE
	WHEN YOU SET POINTS, CLICK "L" FOR LINE MODE
							   "S" FOR SEGMENT MODE
							   "R" FOR RAY MODE
							   "C" FOR CIRCLE MODE
							   THEN CLICK ENTER TO CREATE CHOSEN OBJECT

	PICKING OBJECT:
		USE "A" AND "D".
		PICKED OBJECT WILL HAVE BLACK COLOR
		WHEN YOU PICKED OBJECT, USE ARROW BUTTONS TO MOVE IT ACROSS THE PLANE

	DELETING OBJECTS:
		WHILE PICKING OBJECT, YOU CAN DELETE IT BY CLICKING "BACKSPACE" BUTTON OR "CTRL+Z" COMBINATION
						      YOU CAN RETURN OBJECT BACK ON PLANE BY "CTRL+V" COMBINATION

	INTERACTING WITH OBJECT CLOSER:
		WHEN YOU PICKED OBJECT, CLICK ENTER TO GO IN CONSOLE FOR MORE INTERACTION
		FOR EXAMPLE: WHILE TRIANGLE PICKED, YOU CAN BUILD MEDIANS, ALTITUDES IN CONSOLE AND GO BACK TO EDITOR

	COLOR INSIDE:
		WHEN YOU PICKED OBJECT, CLICK "F" TO DELETE COLOR INSIDE 
*/